name: running_on_dart
version: 1.0.0
description: Discord Bot for nyxx development
author: Szymon Uglis <szymon.uglis@tuta.io>
homepage: https://github.com/l7ssha/running_on_dart
repository: https://github.com/l7ssha/running_on_dart
documentation: https://github.com/l7ssha/nyxx/running_on_dart
issue_tracker: https://github.com/l7ssha/nyxx/running_on_dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  logging: "^1.0.0"
  nyxx: "^2.0.0-rc.6"
  nyxx_commander: "^2.0.0-rc.9"
  nyxx_interactions: "^2.0.0-rc.7"
  time_ago_provider: "^4.0.0"
  sembast: "^3.1.0+2"
