name: running_on_dart
version: 3.3.2
description: Discord Bot for nyxx development
homepage: https://github.com/nyxx-discord/running_on_dart
repository: https://github.com/nyxx-discord/running_on_dart
documentation: https://github.com/nyxx-discord/running_on_dart
issue_tracker: https://github.com/nyxx-discord/running_on_dart/issues
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  duration: ^3.0.11
  fuzzy: ^0.4.0-nullsafety.0
  github: ^9.2.0
  http: ^0.13.4
  human_duration_parser: ^2.0.1
  intl: ^0.17.0
  logging: ^1.0.2
  migent:
    git: https://github.com/nyxx-discord/migent.git
  nyxx: ^4.3.0
  nyxx_commands: ^4.2.0
  nyxx_interactions: ^4.1.0
  nyxx_pagination: ^2.2.0
  nyxx_lavalink: ^3.0.1
  postgres: ^2.4.3
  prometheus_client: ^1.0.0
  prometheus_client_shelf: ^1.0.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2

dev_dependencies:
  lints: ^1.0.1
